### PR TITLE
Initial commit of chart

### PR DESCRIPTION
**Pull request by max-rocket-internet**

### CODE REVIEW

**Comment by cyberw** [comment]
I dont know enough about helm to review :)

Do you have permissions to do the merge yourself?

**Comment by max-rocket-internet** [comment]
Yep.

@cyberw can you fix the main branch setting in this repo? I think it's not set to master?

**Comment by cyberw** [comment]
I cant, or at least I cant find a way to do it. @heyman?

**Comment by heyman** [comment]
Huh, weird that it wasn't default! Fixed now!

**Pull request merged**
